### ISSUE TITLE
"Backup does not contain any manga." when there's only anime history to backup.

### ISSUE THREAD

**Issue by orariley70** [aniyomiorg/aniyomi#1053]
### Steps to reproduce

1. Use Aniyomi to watch anime, but don't add any anime library items
2. Backup

### Expected behavior

Backup should contain anime history as item to backup

### Actual behavior

Backup fails with "Backup does not contain any manga."

### Aniyomi version

Stable 0.12.3.10 (9/2/23 17:47)

### Android version

Android 13

### Device

Google Pixel 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
This has been fixed in the preview

https://github.com/aniyomiorg/aniyomi-preview

Steps to shift to this build:- 
1. Create a backup from "Backup and Restore"
2. Download the preview apk and install it
3. Restore the backup you created before in the same tab "Backup and Restore"


If it still doesnt work, use the website to download the extensions

https://tachiyomi.org/extensions/
