### ISSUE TITLE
Can't install update, says device is not compatible

### ISSUE THREAD

**Issue by maggotb** [aniyomiorg/aniyomi#119]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to the **[latest version](https://github.com/jmir1/aniyomi/releases)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

### Aniyomi version

Preview r3864

### Android version

7.1.1

### Device

Samsung Galaxy Tab SM-T550

### Steps to reproduce

In "About" menu > Check for updates > Download

### Expected behavior

The update should install

### Actual behavior

The update downloads but I can't install it, it says "This app is not compatible with your phone"

### Other details

I tried clearing the cache, it didn't help

**Comment by H3LLB0Y101** [comment]
@maggotb  I had the same issue, but then i backed up my libraries, deleted the app, came onto the release page, and downloaded the correct build version for my device and this worked when i had installed it. Hopefully this can work for you until they develop a way so that you can download the  compatible build version via the app rather than downloading directly from the release page.

**Comment by maggotb** [comment]
@H3LLB0Y101 Thanks it worked, didn't even have to uninstall. The problem still stands though because it's way more convenient to download/install via the app
