### ISSUE TITLE
Manga extensions error

### ISSUE THREAD

**Issue by DeusCMZ** [aniyomiorg/aniyomi#1274]
### Steps to reproduce

Open manga extensions tab

### Expected behavior

It should load the manga extensions list

### Actual behavior

It doesn't load the full manga extensions list but only some
Also, all my previous installed extensions are tagged as 
![Screenshot_2024-01-13-14-43-54-662_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/156540461/f844f792-8a6c-4b85-be15-a48281ce12cb)
![Screenshot_2024-01-13-14-44-03-135_xyz jmir tachiyomi mi debug](https://github.com/aniyomiorg/aniyomi/assets/156540461/30b65cbb-c5e5-4cd4-8503-965caaacad50)
obsoletes 

### Aniyomi version

0.15.2.0-7443

### Android version

Android 13

### Device

Redmi 10C

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Iamslade** [comment]
Same Problem

**Comment by Ramanath11** [comment]
Well, that is due to discontinuation of the Tachiyomi project. They do not support any manga extensions officially due to which, the latest and final version of tachiyomi (0.15.2) doesnt support the older versions of manga source extensions. I am assuming that the Aniyomi team is just working on updates for anime source extensions. 

That being said, there are some other teams who are working on updates for the manga extensions such as [Keiyoushi](https://keiyoushi.github.io/extensions/extensions/). 
- You can search and download your required extension and install them like how you normally install an apk from external source.
- Head to the manga extensions page in Aniyomi and click on "I trust this source" (nothing concerning, this message appears in aniyomi since you installed the extension from an external source)

that should be it... I hope this was helpful...

**Comment by Secozzi** [comment]
@Ramanath11 Do not share third party extension repositories.
