### ISSUE TITLE
[❓QS] All my manga extensions disappeared when I installed the new update

### ISSUE THREAD

**Issue by BrandiUwU** [aniyomiorg/aniyomi#1281]
### Steps to reproduce

![Screenshot_20240114_112831_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/129299867/ccc3b78b-403b-4494-bc30-41c336a1b18e)
![Screenshot_20240114_112722_Aniyomi](https://github.com/aniyomiorg/aniyomi/assets/129299867/ff70b254-2932-4594-a499-c4f3fed7e57d)

### Expected behavior

Should've had Mangakakalot, MangaDex and a lot other manga extensions.

### Actual behavior

All of the old manga extensions disappeared, only left with the ones above that don't work. 

### Aniyomi version

0.15.2.0

### Android version

Android 13

### Device

Samsung Galaxy A71

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] If this is an issue with an official manga extension and this issue can be replicated in the Tachiyomi app, that I should be opening an issue in [Tachiyomi's extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.0](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by xianyu-one** [comment]
I think you can take a look at this https://tachiyomi.org/news/2024-01-09-extensions-removal

Tachiyomi removed the official plugin library due to pressure

If you want to add a plug-in library, you can use the following URL: https://keiyoushi.github.io/extensions/

**Comment by abdallahmehiz** [comment]
@xianyu-one do not share 3rd party extensions repositories

**Comment by Iamslade** [comment]
Same problem

**Comment by GorskaAzdaja** [comment]
Isn't the intended behaviour to be able to install extensions from the app itself? For me the anime part works just fine, I didn't even need to reinstall the extension, but the manga was completely broken rendering that part of the app unusable. Did the method change for installing manga extensions?

**Comment by NameLessGO** [comment]
Not a bug, users will have to bring their own content to Aniyomi

The reasoning about this decision can be read here, but in short, it is to avoid potential lawsuits and maintain Aniyomi  longevity (incl forks)

https://tachiyomi.org/news/2024-01-09-extensions-removal

See this post for updates about the future of tachiyomi and Aniyomi forks

https://lemm.ee/post/20876051

**Comment by andrixpan** [comment]
RIP. unistall aniyomi.. it's no longer useful..

**Comment by abdallahmehiz** [comment]
@NameLessGo do not share 3rd party extensions repositories

**Comment by Iamslade** [comment]
> This known behavior, afaik. You will need to add an extension repo.
> 
> This is copied from discord:
> 
> > IMPORTANT : When updating to the latest stable you NEED to uninstall all the previous extensions related to tachiyomi.
> > Since some of them don't show up in Aniyomi follow this simple steps:
> > 1)Go to the settings of your phone
> > 2)Manage your apps
> > 3)Search for "Tachiyomi" to show all the extensions
> > 4) Delete all of them
> > That's it , now you can install them all back from the repo you added
> 
> also:
> 
> > example for manga repos:`https://raw.githubusercontent.com/username/repo/repo/index.min.json`
> > example for anime repos:`aniyomi://https://raw.githubusercontent.com/username/repo/repo/index.min.json`
> 
> Please do not link any of these repositories here of in discord.

Still not working for me.

**Comment by Iamslade** [comment]
https://keiyoushi.github.io/extensions/

1.Open this
2.Add it and enjoy
Solved

**Comment by rhd4199** [comment]
> > This known behavior, afaik. You will need to add an extension repo.
> > This is copied from discord:
> > > IMPORTANT : When updating to the latest stable you NEED to uninstall all the previous extensions related to tachiyomi.
> > > Since some of them don't show up in Aniyomi follow this simple steps:
> > > 1)Go to the settings of your phone
> > > 2)Manage your apps
> > > 3)Search for "Tachiyomi" to show all the extensions
> > > 4) Delete all of them
> > > That's it , now you can install them all back from the repo you added
> > 
> > 
> > also:
> > > example for manga repos:`https://raw.githubusercontent.com/username/repo/repo/index.min.json`
> > > example for anime repos:`aniyomi://https://raw.githubusercontent.com/username/repo/repo/index.min.json`
> > 
> > 
> > Please do not link any of these repositories here of in discord.
> 
> Still not working for me.

same as me, it didn't work, help please !!

**Comment by Destro9000** [comment]
@rhd4199 did you remove all the extensions from your phone ?

**Comment by rhd4199** [comment]
> @rhd4199 did you remove all the extensions from your phone ?

yes i did 
i remove both all aniyomi extensions and all tachiyomi extensions 

i even reinstall this new version again, but still didnt work either @Destro9000 

in language button on manga extension there is only 1 option -> multi 
there is no other option

**Comment by rhd4199** [comment]
> @rhd4199 did you add a third party repository for your manga?

nope, i never add a third party repository, or even local repository, i only use extension that have given by apps  @Destro9000

**Comment by Destro9000** [comment]
You need to add a third-party repository for your manga extensions , since tachiyomi got taken down and removed the repo.

Do your own search for that , no repo recommendations or questions

**Comment by rhd4199** [comment]
> You need to add a third-party repository for your manga extensions , since tachiyomi got taken down and removed the repo.
> 
> Do your own search for that , no repo recommendations or questions

damn that sad, so no help then ?

**Comment by JackDSRS** [comment]
Aniyomi's manga potion is built on essentually a fork of Tachiyomi. The old extensions/repos purposely don't work with the new Tachiyomi extension/repo format quite the same way, and Tachiyomi abandoned the old extension format as Not installed or Untrusted. These 4 new repos are global and get around a lot of issues like Cloudflare, etc.

The 4 new extensions/repos (Kavita, etc) do have a documented setup procedure for Tachiyomi on the EXTENSION/REPO sites, not the Tachiyomi site but the same interface isn't available in the forks: TachiyomiSY and Aniyomi's manga portion.

I don't have the answer, just clues and guesses about forks code updated in isolation from the original apps GUI without testing. Otherwise this would't be such a PITA to solve. Since Tachiyomi stopped development and support, I don't know what will happen.

I do know the Discord servers are pretty much useless. 

I have the last good set of repos in APK  format and I'll be glad to share. Locally installed, most still limp along at least when I restored my old version of TachiyomiSY. Not sure how they'll work with Aniyomi.

**Comment by Roswaal12** [comment]
> I have the last good set of repos in APK format and I'll be glad to share. Locally installed, most still limp along at least when I restored my old version of TachiyomiSY. Not sure how they'll work with Aniyomi.

Does rule 4 violation apply on github as well?

**Comment by Secozzi** [comment]
Please do not share third party extension repos on GitHub.

**Comment by JackDSRS** [comment]
> Please do not share third party extension repos on GitHub.

Better?

**Comment by JackDSRS** [comment]
I have a band-aid fix that may or may not work for you. It will allow you to limp along, do searches, migrate, and may restore covers and info. At least it worked for me.

If, and only if, you backup your apps themselves, not meaning the regular Aniyomi internal backup, see if you've got backups of the Tachiyomi APK's. These are the repos for your manga. They'll look like Tachiomi: AZManhua, or eu.kanade.tachiyomi.extension.en.azmanhua or Tachiyomi_ AZManhwa [1.4.32].apk. Some variation of that. If you do have them, restore them.

As you restore them, depending on the method, they may appear immediately under your manga extension list. During installation or after restarting Aniyomi, they'll say OBSOLETE. I'm guessing its because these are no longer in Tachiyomi's GitHub repository. Don't uninstall them. Check their language and adult setting as these won't have been restored.

I kept a backup of the big 4, Kavita & Co, then uninstalled them until someone makes them easier to understand. This also speeds up search time since they'll just kick back errors or timeouts for me as I can't install them correctly yet.

With Aniyomi's changes, when searching, pick All and Results. For now, Pinned will limit your searches to your pinned extensions, not just listing them at the top with the rest of the search results. You get nothing if you've Pinned nothing.

That seemed to at least make the Manga part start working again for me. I tested searches, updates, migrating sources, etc. Some of the extensions just don't work anymore as they were obsolete before Tachiyomi's big changes.

**Comment by andrixpan** [comment]
> RIP. unistall aniyomi.. it's no longer useful..

my friend still using old version and he can read manhwa use old extensions. so unistall new version and install old version, tips backup your database to keep the setting, and use apkeditor to modify extensions to add new manga or manhwa site..

**Comment by JackDSRS** [comment]
Actually, I kept Aniyomi for anime and a surprising amount of western
movies and TV.

I used the backup, and installed Tachiyomi 1.10.1, not the most recent
version. That version was the new format but still allowed custom repos
through the index.min.json format.

I restored the new Aniyomi backup into the TachiyomiSY app and changed some
of the settings. Then I installed some definately unapproved Extension
repos under the Settings, Browse section using the index.min.json format.

Then came the pain in the butt. All the new extensions I chose to keep had
to be toggled to Trusted. Then each of their settings needed checked.

I went back into my Library and migrated anything that needed it.

Once I was done, I backed up TachiyomySY.

THEN I went back into Aniyomi and gutted out all my manga library only.
Since my actual manga and anime are not stored in the Aniyomi or
TachiyomiSY file structures after they're downloaded (I move them elsewhere
and use the programs as a reference and downloaders) deleting the manga
libraries didn't affect the actual manga.

I did NOT delete the manga repo extensions. Doing this would also delete
them from TachiyomiSY. Since I can't hide them in Aniyomi, I'll just have
to ignore them.

Now Aniyomi can update gracefully no matter what affects the death of the
main Tachiyomi program had, my anime libraries are still intact.

My manga libraries are intact in TachiyomiSY and at least in version 1.10.1
I can still update repos like in Aniyomi, search, and download like before.
The newest version of TachiyomiSY has moved away from the index.min.json
format making pulling in unkosher repos harder, so they're not as easily
updated. That's why I specified that version.

Aniyomi remains great for anime, movies, and tv. The death of Tachiomi
proper made any manga forks a mess. By seperating the manga away from
Aniyomi, you fix all of Aniyomi's issues with manga permanently. It just
takes a lot of work, time, and patience.

**Comment by JackDSRS** [comment]
I stand corrected. Mihon is using Kavita, etc. as well.

You have to set up your own server with a fixed IP, blah, blah, blah.

There are lots of PC options, including one or two I'm still licensed for.
I may resort to some cloud synching tricks for this. Since I have pCloud, I
don't have to worry as much about Google mucking about in my stuff.

Sorry about the other fork mentions. Its just the same manga code was
brought into Aniyomi as well.
