### ISSUE TITLE
Frequent errors while trying to play anime

### ISSUE THREAD

**Issue by Mizumaky** [aniyomiorg/aniyomi#285]
## Device information
* Aniyomi version: 0.12.3.5
* Android version: 9
* Device: Sony Xperia XZ1

## Issue
I am encountering errors quite often when trying to play an episode, this includes:
* HTTP 403 error
* an SSL error with a long message 
* "can't open this link" while playing via MX Player

## When it happens 
I havent yet identified a specific pattern. Although for example, currently:
 1. I opened episode 16 and played 2 seconds of it
 2. Then I played whole episode 15
 3. I wanted to continue with 16, but got HTTP 403
 4. I tried ep 15 again, but now i also get HTTP 403
 5. I closed the app, waited some time, opened it again, and played 16 - now it works

## Other details
* I am normally using external MX Player, but I have checked that the errors happen for internal player too (after I encountered a HTTP 403 now, I switched to internal and it happened too)
* I have the same anime from multiple sources (Animepahe, Genoanime, Gogoanime, tenshi.moe), and when I can't play an episode at one source, errors often happen on other sources too. Sometimes I find a working one, but  sometimes I have to solve it differently (eg i added the anime from a new extension i havent used yet, or i closed aniyomi and waited, etc)

**Comment by Ugaog123** [comment]
Same, I used to open the links into VLC ao i can cast to my TV but the links stopped working. But I think it's a problem with the source itself rather than Aniyomi cause I tried putting link myself and its still not working. Even the casting options on the sites themselves dont work. One thing that works for definite is downloading the episode and casting it locally.
