### ISSUE TITLE
External player issue :vlc

### ISSUE THREAD

**Issue by brodiebear** [aniyomiorg/aniyomi#855]
### Steps to reproduce

Set external player
Select video

Vlc not working. Coming up with xml error

Can we get this fixed ? I cannot cast without Vlc

### Expected behavior

Vlc should play. And i should be able to cast anime to the tv. It has worked in the past

### Actual behavior

Xml error. No links play when using external player , vlc

### Aniyomi version

Latest version

### Android version

Latest version

### Device

Samsung devices. 22 ultra + tablet 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Adamekka** [comment]
you need to use the built-in player

**Comment by iDragonzz-NW** [comment]
This issue was created because they can't use the built-in video player for their own reasons, it no use telling them this as that's the entire reason for issue threads. 

I am also having the same issue, I'm not entirely sure but it may be due to a recent update from the VLC team.
I've attached a screenshot of the error but as it's an android toast this is the most I can see. 
![Screenshot_20221220-203459](https://user-images.githubusercontent.com/47451987/208762180-cb8f496b-f284-43f7-b3d2-05ee76b5de71.png)

**Comment by warior456** [comment]
You can get around this by selecting external player and preference none and then selecting vlc from the popup that asks what app
