### ISSUE TITLE
We want old player back

### ISSUE THREAD

**Issue by RuDru-OP** [aniyomiorg/aniyomi#975]
### Describe your suggested feature

In the preview version, It should either be a little minimal I dont want much feature on my screen...Or bring the old player back but just keep the subtitle option on the screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [ ] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**.
- [ ] I will fill out all of the requested information in this form.

**Comment by Helpful-Neko** [comment]
The new player is better

**Comment by RuDru-OP** [comment]
> The new player is better

Bro when I used The old plater it just used to work fine but now it buffer every single second...My network is still the same and the extension too

**Comment by lewdpatriot** [comment]
Not 'we', it's only you. And if you have a problem with preview version use the stable for now. It's called preview for a reason.

**Comment by lewdpatriot** [comment]
> Its my opinion no one asked you to take it offensively.

Sorry, I see now my phrasing was wrong and you're absolutely right. I typed without thinking clearly because I love the new player so much. I even moved most of the videos to ./aniyomi/localfiles to access them from aniyomi . 😅

But the buffering issue should not be the player's fault, something else is probably causing it. And I think all the buttons on the player are necessary. ( There is a setting where you can edit the player config but I haven't found any documentation on how to configure mpv-android yet).
